'''
Each new term in the Fibonacci sequence
is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence
whose values do not exceed four million,
find the sum of the even-valued terms.
'''

prev1 = 1
prev2 = 0
sum = 0
while prev1 + prev2 < 4000000:
    fib = prev1 + prev2
    if fib % 2 == 0:
        sum += fib
    prev2 = prev1
    prev1 = fib
print(sum)
